services:
  - type: web
    name: swopify-backend
    env: docker
    dockerfilePath: ./Dockerfile
    plan: free
    region: oregon
    branch: main
    healthCheckPath: /health
    envVars:
      - key: PORT
        sync: false
      - key: HOST
        value: 0.0.0.0
      - key: ENVIRONMENT
        value: production
      - key: DB_HOST
        sync: false
      - key: DB_PORT
        sync: false
      - key: DB_NAME
        sync: false
      - key: DB_USER
        sync: false
      - key: DB_PASSWORD
        sync: false
